/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ramonserrano
 */
public class RadioView extends javax.swing.JPanel {

    /**
     * Creates new form RadioView
     */
    public RadioView() {
        initComponents();
    }
    
    int subir=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMasVolumen = new javax.swing.JButton();
        btnMenosVolumen = new javax.swing.JButton();
        labelVolumen = new javax.swing.JLabel();

        btnMasVolumen.setText("+");
        btnMasVolumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasVolumenMouseClicked(evt);
            }
        });

        btnMenosVolumen.setText("-");
        btnMenosVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosVolumenActionPerformed(evt);
            }
        });

        labelVolumen.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelVolumen.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenosVolumen)
                    .addComponent(btnMasVolumen))
                .addGap(56, 56, 56)
                .addComponent(labelVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMasVolumen)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenosVolumen)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenosVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosVolumenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenosVolumenActionPerformed

    private void btnMasVolumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasVolumenMouseClicked
        // TODO add your handling code here:
        subir++;
    }//GEN-LAST:event_btnMasVolumenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasVolumen;
    private javax.swing.JButton btnMenosVolumen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelVolumen;
    // End of variables declaration//GEN-END:variables
}
